clone_depth: 1
version: '{branch}-{build}'
image: Visual Studio 2017
configuration: Debug
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
install:
  - cmd: git submodule update --init --recursive --depth=5
  - cmd: choco install resharper-clt -y
  - cmd: choco install nvika -y
  - cmd: dotnet tool install CodeFileSanity --version 0.0.16 --global
  - cmd: choco install opencover.portable
  - cmd: choco install dotnetcore-sdk
  #- cmd: choco install codecov
before_build:
  - cmd: CodeFileSanity
  - cmd: nuget restore -verbosity quiet
build:
  project: osu.sln
  parallel: true
  verbosity: minimal
test_script:
  - OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test "-filter:+[osu.Game.Rulesets.Catch]* +[osu.Game.Rulesets.Osu]* +[osu.Game.Rulesets.Mania]* +[osu.Game.Rulesets.Taiko]* +[osu.Game]*" -output:".\MyProject_coverage.xml" -oldstyle
 #- codecov -f "MyProject_coverage.xml"
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "MyProject_coverage.xml"
after_build:
  - cmd: inspectcode --o="inspectcodereport.xml" --projects:osu.Game* --caches-home="inspectcode" osu.sln > NUL
  - cmd: NVika parsereport "inspectcodereport.xml" --treatwarningsaserrors
#refresh